# Generated by Django 5.1.3 on 2024-12-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='def_field',
            new_name='defense',
        ),
    ]
