# Generated by Django 5.1.3 on 2025-01-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='monster_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pend_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='scale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
