# Generated by Django 5.1.3 on 2025-01-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_card_monster_desc_card_pend_desc_card_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='konamy_id',
            field=models.IntegerField(default='1'),
        ),
    ]
