# Generated by Django 5.1.3 on 2025-01-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_konamy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='konamy_id',
            new_name='konami_id',
        ),
    ]
