# Generated by Django 5.1.3 on 2025-01-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_rename_konamy_id_card_konami_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='konami_id',
        ),
    ]
