# Generated by Django 5.1.3 on 2025-01-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_remove_card_konami_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='konami_id',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
