# Generated by Django 5.1.3 on 2024-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_def_field_card_defense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_sets',
            field=models.ManyToManyField(related_name='cards', to='cards.cardset'),
        ),
    ]
