# Generated by Django 5.1.3 on 2024-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_card_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
