# Generated by Django 5.1.3 on 2024-12-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_attribute_alter_card_typeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='frame_type',
            new_name='frameType',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='human_readable_card_type',
            new_name='humanReadableCardType',
        ),
    ]
